version: '3.8'

services:
  runner:
    image: runner-docker-1
    container_name: yyyyyyyyy
    restart: always
    environment:
      - REPO=ejemplo-organizacion-sms
      - REG_TOKEN=XXXXXXXXX
      - NAME=runner-docker