name: build and deploy runner github

on:
  push:
    branches: ["main"]

env:
  VERSION_DOCKER: ${{vars.VERSION_DOCKER}}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v5

      - name: build de docker sin action
        run: |
          docker build -t mi-runner-de-github:${{ env.VERSION_DOCKER }} .